export const FAQ = [
  ['Is my video uploaded anywhere?', 'No. All processing happens locally in your browser using FFmpeg WASM. There is no backend or upload — your files never leave your device.'],
  ['Why MKV → MP4?', 'MP4 is universally compatible (especially on Android and iOS), while MKV is a flexible container often used for anime and rips with multiple subtitle tracks.'],
  ['What subtitle formats are supported?', 'SSA, ASS, SRT, PGS, VobSub, SUB, and WebVTT detection. Soft-mux uses mov_text; burn-in renders ASS/SSA styling via FFmpeg subtitles filter.'],
  ['What is Fast Remux (Mode A)?', 'It copies the video and audio streams without re-encoding (stream copy), so it’s extremely fast and lossless. Subtitle is extracted to SRT alongside.'],
  ['What is Soft Subtitle (Mode B)?', 'Subtitle is embedded as mov_text inside the MP4. Compatible with most modern players.'],
  ['What is Burn Subtitle (Mode C)?', 'Subtitle is baked into the video pixels. Required when you need ASS/SSA styling (anime karaoke, positioning) to look the same everywhere.'],
  ['What is Hybrid Android Mode (Mode D)?', 'Burns subtitle into the video for max compatibility AND exports an SRT backup. Ideal for older Android players.'],
  ['Does it support batch conversion?', 'Yes — up to 100 files per session with a queue, progress, ETA, retry, pause, and ZIP batch download.'],
  ['Does it work offline?', 'Yes. The app is a PWA and caches the FFmpeg core so you can reopen and convert without internet.'],
  ['Can I install it as an app?', 'Yes, click Install in the header (where supported) or use “Add to Home Screen” on mobile.'],
  ['How large can the files be?', 'Limited by your device RAM. Most browsers handle several GB; very large files may need a desktop browser.'],
  ['Is quality preserved?', 'In Remux and Soft modes, yes — streams are copied. Burn mode re-encodes video (CRF 22, veryfast preset) for compatibility.'],
  ['Does it preserve resolution and FPS?', 'Yes, resolution and FPS are preserved in all modes. Bitrate is preserved in copy modes.'],
  ['Why is the first load slow?', 'It downloads ~31 MB of FFmpeg WASM core, then caches it. Subsequent loads are instant.'],
  ['Why does my browser ask about cross-origin isolation?', 'FFmpeg WASM uses SharedArrayBuffer, which requires COOP/COEP headers on some hosts. Most modern hosts work; if not, the engine falls back to single-thread mode.'],
  ['Can I convert without internet after first load?', 'Yes — the service worker caches the app shell and FFmpeg core. Reopen the page offline and convert.'],
  ['Where are my files stored?', 'Only in memory during conversion. IndexedDB only stores queue metadata and cached engine assets — not your videos.'],
  ['Does it support folder upload?', 'Yes, click 📁 Folder or drag a folder into the dropzone (Chromium-based browsers).'],
  ['Is there any tracking or analytics?', 'No. Zero tracking, zero cookies, zero analytics.'],
  ['Can I self-host?', 'Yes — deploy the static files to Vercel, Netlify, Cloudflare Pages, GitHub Pages, or any static server.'],
];
